// Realistic mock data for offline/fallback use
// Route coordinates follow the actual Alandi → Pandharpur Wari pilgrimage path

export const WARI_STOPS = [
  { id: 'alandi', nameKey: 'stops.alandi', lat: 18.6776, lng: 73.8985 },
  { id: 'dehu', nameKey: 'stops.dehu', lat: 18.7140, lng: 73.7672 },
  { id: 'pune', nameKey: 'stops.pune', lat: 18.5204, lng: 73.8567 },
  { id: 'loni_kalbhor', nameKey: 'stops.loni_kalbhor', lat: 18.5062, lng: 73.9867 },
  { id: 'saswad', nameKey: 'stops.saswad', lat: 18.3454, lng: 74.0321 },
  { id: 'jejuri', nameKey: 'stops.jejuri', lat: 18.2731, lng: 74.1603 },
  { id: 'valhe', nameKey: 'stops.valhe', lat: 18.1500, lng: 74.2400 },
  { id: 'lonand', nameKey: 'stops.lonand', lat: 18.0186, lng: 74.4489 },
  { id: 'taradgaon', nameKey: 'stops.taradgaon', lat: 17.9000, lng: 74.5400 },
  { id: 'phaltan', nameKey: 'stops.phaltan', lat: 17.7837, lng: 74.4328 },
  { id: 'baradwadi', nameKey: 'stops.baradwadi', lat: 17.6500, lng: 74.5100 },
  { id: 'natepute', nameKey: 'stops.natepute', lat: 17.6300, lng: 74.5300 },
  { id: 'velapur', nameKey: 'stops.velapur', lat: 17.5800, lng: 74.5700 },
  { id: 'bhandishegaon', nameKey: 'stops.bhandishegaon', lat: 17.5500, lng: 74.5900 },
  { id: 'wakhari', nameKey: 'stops.wakhari', lat: 17.6200, lng: 75.1000 },
  { id: 'pandharpur', nameKey: 'stops.pandharpur', lat: 17.6778, lng: 75.3267 },
];

export const WARI_ROUTE_OPTIONS = [
  {
    id: 'dnyaneshwar',
    nameKey: 'routes.dnyaneshwar_route',
    name: 'Sant Dnyaneshwar Maharaj Palkhi Route',
    origin: 'Alandi',
    destination: 'Pandharpur',
    distanceKm: 245,
    durationDays: 18,
    walkingHours: 56,
    color: '#EA580C',
    tagKey: 'routes.primary_palkhi',
    description: 'Main Sant Dnyaneshwar Palkhi via Saswad, Dive Ghat, Jejuri, Lonand, Phaltan, Velapur to Pandharpur',
    segments: [
      {
        id: 'dn_1',
        nameKey: 'routes.alandi_pune',
        name: 'Alandi → Pune (Sangamwadi)',
        distanceKm: 22,
        walkingHours: 5,
        crowd_count: 850,
        status: 'orange',
        coordinates: [
          { lat: 18.6776, lng: 73.8985 },
          { lat: 18.6480, lng: 73.8820 },
          { lat: 18.6150, lng: 73.8710 },
          { lat: 18.5700, lng: 73.8640 },
          { lat: 18.5204, lng: 73.8567 },
        ],
      },
      {
        id: 'dn_2',
        nameKey: 'routes.pune_saswad',
        name: 'Pune → Saswad (via Dive Ghat)',
        distanceKm: 31,
        walkingHours: 7.5,
        crowd_count: 1420,
        status: 'red',
        coordinates: [
          { lat: 18.5204, lng: 73.8567 },
          { lat: 18.5040, lng: 73.9320 },
          { lat: 18.4650, lng: 73.9750 },
          { lat: 18.4200, lng: 74.0050 },
          { lat: 18.3800, lng: 74.0200 },
          { lat: 18.3454, lng: 74.0321 },
        ],
      },
      {
        id: 'dn_3',
        nameKey: 'routes.saswad_jejuri',
        name: 'Saswad → Jejuri',
        distanceKm: 18,
        walkingHours: 4,
        crowd_count: 620,
        status: 'green',
        coordinates: [
          { lat: 18.3454, lng: 74.0321 },
          { lat: 18.3200, lng: 74.0700 },
          { lat: 18.2950, lng: 74.1150 },
          { lat: 18.2731, lng: 74.1603 },
        ],
      },
      {
        id: 'dn_4',
        nameKey: 'routes.jejuri_lonand',
        name: 'Jejuri → Lonand (via Valhe)',
        distanceKm: 24,
        walkingHours: 5.5,
        crowd_count: 780,
        status: 'orange',
        coordinates: [
          { lat: 18.2731, lng: 74.1603 },
          { lat: 18.2100, lng: 74.2000 },
          { lat: 18.1500, lng: 74.2400 },
          { lat: 18.0800, lng: 74.3300 },
          { lat: 18.0186, lng: 74.4489 },
        ],
      },
      {
        id: 'dn_5',
        nameKey: 'routes.lonand_phaltan',
        name: 'Lonand → Phaltan (via Taradgaon)',
        distanceKm: 34,
        walkingHours: 8,
        crowd_count: 1250,
        status: 'red',
        coordinates: [
          { lat: 18.0186, lng: 74.4489 },
          { lat: 17.9500, lng: 74.4900 },
          { lat: 17.9000, lng: 74.5400 },
          { lat: 17.8400, lng: 74.5000 },
          { lat: 17.7837, lng: 74.4328 },
        ],
      },
      {
        id: 'dn_6',
        nameKey: 'routes.phaltan_natepute',
        name: 'Phaltan → Natepute (via Barad)',
        distanceKm: 38,
        walkingHours: 9,
        crowd_count: 420,
        status: 'green',
        coordinates: [
          { lat: 17.7837, lng: 74.4328 },
          { lat: 17.7100, lng: 74.4750 },
          { lat: 17.6500, lng: 74.5100 },
          { lat: 17.6300, lng: 74.5300 },
        ],
      },
      {
        id: 'dn_7',
        nameKey: 'routes.natepute_velapur',
        name: 'Natepute → Velapur (via Malshiras)',
        distanceKm: 28,
        walkingHours: 6.5,
        crowd_count: 510,
        status: 'green',
        coordinates: [
          { lat: 17.6300, lng: 74.5300 },
          { lat: 17.6050, lng: 74.5500 },
          { lat: 17.5800, lng: 74.5700 },
        ],
      },
      {
        id: 'dn_8',
        nameKey: 'routes.velapur_pandharpur',
        name: 'Velapur → Pandharpur (via Wakhari Ringan)',
        distanceKm: 50,
        walkingHours: 11,
        crowd_count: 1850,
        status: 'red',
        coordinates: [
          { lat: 17.5800, lng: 74.5700 },
          { lat: 17.5500, lng: 74.5900 },
          { lat: 17.5800, lng: 74.8200 },
          { lat: 17.6200, lng: 75.1000 },
          { lat: 17.6778, lng: 75.3267 },
        ],
      },
    ],
  },
  {
    id: 'tukaram',
    nameKey: 'routes.tukaram_route',
    name: 'Sant Tukaram Maharaj Palkhi Route',
    origin: 'Dehu',
    destination: 'Pandharpur',
    distanceKm: 218,
    durationDays: 18,
    walkingHours: 50,
    color: '#2563EB',
    tagKey: 'routes.tukaram_palkhi',
    description: 'Sant Tukaram Palkhi via Akurdi, Pune, Loni Kalbhor, Yawat, Baramati, Indapur, Akluj to Pandharpur',
    segments: [
      {
        id: 'tk_1',
        nameKey: 'routes.dehu_pune',
        name: 'Dehu → Pune (Nivdungya Vitthal Mandir)',
        distanceKm: 28,
        walkingHours: 6.5,
        crowd_count: 920,
        status: 'orange',
        coordinates: [
          { lat: 18.7140, lng: 73.7672 },
          { lat: 18.6500, lng: 73.7900 },
          { lat: 18.5800, lng: 73.8200 },
          { lat: 18.5204, lng: 73.8567 },
        ],
      },
      {
        id: 'tk_2',
        nameKey: 'routes.pune_lonikalbhor',
        name: 'Pune → Loni Kalbhor',
        distanceKm: 18,
        walkingHours: 4,
        crowd_count: 480,
        status: 'green',
        coordinates: [
          { lat: 18.5204, lng: 73.8567 },
          { lat: 18.5100, lng: 73.9200 },
          { lat: 18.5062, lng: 73.9867 },
        ],
      },
      {
        id: 'tk_3',
        nameKey: 'routes.lonikalbhor_yawat',
        name: 'Loni Kalbhor → Yawat & Patas',
        distanceKm: 32,
        walkingHours: 7.5,
        crowd_count: 670,
        status: 'orange',
        coordinates: [
          { lat: 18.5062, lng: 73.9867 },
          { lat: 18.4700, lng: 74.1500 },
          { lat: 18.4350, lng: 74.3100 },
        ],
      },
      {
        id: 'tk_4',
        nameKey: 'routes.patas_baramati',
        name: 'Patas → Baramati',
        distanceKm: 36,
        walkingHours: 8.5,
        crowd_count: 380,
        status: 'green',
        coordinates: [
          { lat: 18.4350, lng: 74.3100 },
          { lat: 18.3000, lng: 74.4500 },
          { lat: 18.1500, lng: 74.5800 },
        ],
      },
      {
        id: 'tk_5',
        nameKey: 'routes.baramati_indapur',
        name: 'Baramati → Indapur',
        distanceKm: 42,
        walkingHours: 9.5,
        crowd_count: 750,
        status: 'orange',
        coordinates: [
          { lat: 18.1500, lng: 74.5800 },
          { lat: 18.1200, lng: 74.8500 },
          { lat: 18.1100, lng: 75.0300 },
        ],
      },
      {
        id: 'tk_6',
        nameKey: 'routes.indapur_akluj',
        name: 'Indapur → Akluj (Sarati Nira Snan)',
        distanceKm: 30,
        walkingHours: 7,
        crowd_count: 1350,
        status: 'red',
        coordinates: [
          { lat: 18.1100, lng: 75.0300 },
          { lat: 17.9500, lng: 75.0200 },
          { lat: 17.8800, lng: 75.0200 },
        ],
      },
      {
        id: 'tk_7',
        nameKey: 'routes.akluj_pandharpur',
        name: 'Akluj → Wakhari Ringan → Pandharpur',
        distanceKm: 32,
        walkingHours: 7,
        crowd_count: 1780,
        status: 'red',
        coordinates: [
          { lat: 17.8800, lng: 75.0200 },
          { lat: 17.7500, lng: 75.0600 },
          { lat: 17.6200, lng: 75.1000 },
          { lat: 17.6778, lng: 75.3267 },
        ],
      },
    ],
  },
  {
    id: 'alternative_green',
    nameKey: 'routes.alternative_route',
    name: 'Green & Safe Bypass Route',
    origin: 'Pune / Saswad Bypass',
    destination: 'Pandharpur',
    distanceKm: 235,
    durationDays: 16,
    walkingHours: 48,
    color: '#10B981',
    tagKey: 'routes.green_bypass',
    description: 'Low-density green bypass route with medical coverage and water hubs for fast assistance',
    segments: [
      {
        id: 'alt_1',
        nameKey: 'routes.pune_morgaon_bypass',
        name: 'Pune → Morgaon Bypass',
        distanceKm: 45,
        walkingHours: 9,
        crowd_count: 180,
        status: 'green',
        coordinates: [
          { lat: 18.5204, lng: 73.8567 },
          { lat: 18.4200, lng: 74.1500 },
          { lat: 18.2800, lng: 74.3100 },
        ],
      },
      {
        id: 'alt_2',
        nameKey: 'routes.morgaon_phaltan_bypass',
        name: 'Morgaon → Phaltan Ring Bypass',
        distanceKm: 55,
        walkingHours: 11,
        crowd_count: 240,
        status: 'green',
        coordinates: [
          { lat: 18.2800, lng: 74.3100 },
          { lat: 18.0500, lng: 74.4000 },
          { lat: 17.7837, lng: 74.4328 },
        ],
      },
      {
        id: 'alt_3',
        nameKey: 'routes.phaltan_karkamb_bypass',
        name: 'Phaltan → Karkamb → Pandharpur Bypass',
        distanceKm: 135,
        walkingHours: 28,
        crowd_count: 310,
        status: 'green',
        coordinates: [
          { lat: 17.7837, lng: 74.4328 },
          { lat: 17.7000, lng: 74.7500 },
          { lat: 17.7200, lng: 75.1500 },
          { lat: 17.6778, lng: 75.3267 },
        ],
      },
    ],
  },
];

export const MOCK_ROUTES = WARI_ROUTE_OPTIONS[0].segments.map(s => ({
  route_id: s.id,
  nameKey: s.nameKey,
  route_name: s.name,
  crowd_count: s.crowd_count,
  status: s.status,
  distanceKm: s.distanceKm,
  walkingHours: s.walkingHours,
  coordinates: s.coordinates,
}));

export const MOCK_POIS = [
  // ── Food Camps / Annachhatra ──────────────────────────────────────────
  { id: 'f1', name: 'Alandi Sant Dnyaneshwar Annachhatra', nameKey: 'pois.alandi_anna', category: 'food', latitude: 18.6776, longitude: 73.8985, contact: '9876543210', capacity_status: 'available', landmark: 'Near Alandi Temple Gate' },
  { id: 'f2', name: 'Dehu Sant Tukaram Bhojan Griha', nameKey: 'pois.dehu_bhojan', category: 'food', latitude: 18.7140, longitude: 73.7672, contact: '9876543211', capacity_status: 'available', landmark: 'Dehu Gatha Mandir' },
  { id: 'f3', name: 'Pune Wari Maha Anna Seva', nameKey: 'pois.pune_anna', category: 'food', latitude: 18.5180, longitude: 73.8550, contact: '9876543215', capacity_status: 'available', landmark: 'Shivaji Nagar Ground' },
  { id: 'f4', name: 'Saswad Devotee Food Pavilion', nameKey: 'pois.saswad_anna', category: 'food', latitude: 18.3470, longitude: 74.0300, contact: '9876543216', capacity_status: 'available', landmark: 'Saswad Palkhi Ground' },
  { id: 'f5', name: 'Jejuri Khandoba Prasad Kendra', nameKey: 'pois.jejuri_prasad', category: 'food', latitude: 18.2731, longitude: 74.1603, contact: '9876543212', capacity_status: 'full', landmark: 'Jejuri Fort Base' },
  { id: 'f6', name: 'Lonand Warkari Maha Bhandara', nameKey: 'pois.lonand_bhandara', category: 'food', latitude: 18.0186, longitude: 74.4489, contact: '9876543213', capacity_status: 'available', landmark: 'Lonand Market Yard' },
  { id: 'f7', name: 'Phaltan Royal Annadan Seva', nameKey: 'pois.phaltan_anna', category: 'food', latitude: 17.7820, longitude: 74.4310, contact: '9876543217', capacity_status: 'available', landmark: 'Phaltan Palkhi Maidan' },
  { id: 'f8', name: 'Velapur Seva Samiti Food Camp', nameKey: 'pois.velapur_anna', category: 'food', latitude: 17.5790, longitude: 74.5710, contact: '9876543218', capacity_status: 'available', landmark: 'Velapur High School' },
  { id: 'f9', name: 'Wakhari Ringan Annadan Kendra', nameKey: 'pois.wakhari_anna', category: 'food', latitude: 17.6220, longitude: 75.1020, contact: '9876543219', capacity_status: 'available', landmark: 'Wakhari Ringan Ground' },
  { id: 'f10', name: 'Pandharpur Vitthal Annadan Mahaprasad', nameKey: 'pois.pandharpur_annadan', category: 'food', latitude: 17.6778, longitude: 75.3267, contact: '9876543214', capacity_status: 'available', landmark: 'Temple Annachhatra Bhavan' },

  // ── Hospitals & Medical Camps ─────────────────────────────────────────
  { id: 'm1', name: 'Alandi PHC & Emergency Camp', nameKey: 'pois.alandi_med', category: 'medical', latitude: 18.6750, longitude: 73.9000, contact: '108', capacity_status: 'available', landmark: 'Alandi Rural Hospital' },
  { id: 'm2', name: 'Pune Sassoon Hospital Wari ICU Camp', nameKey: 'pois.pune_med', category: 'medical', latitude: 18.5250, longitude: 73.8680, contact: '108', capacity_status: 'available', landmark: 'Near Pune Railway Station' },
  { id: 'm3', name: 'Saswad Trauma Care Center', nameKey: 'pois.saswad_med', category: 'medical', latitude: 18.3440, longitude: 74.0310, contact: '108', capacity_status: 'available', landmark: 'Saswad Civil Hospital' },
  { id: 'm4', name: 'Jejuri Emergency Medical Unit', nameKey: 'pois.jejuri_med', category: 'medical', latitude: 18.2700, longitude: 74.1620, contact: '108', capacity_status: 'available', landmark: 'Near Jejuri Bus Depot' },
  { id: 'm5', name: 'Lonand 24x7 Ambulance & First Aid', nameKey: 'pois.lonand_med', category: 'medical', latitude: 18.0190, longitude: 74.4470, contact: '108', capacity_status: 'available', landmark: 'Lonand Junction' },
  { id: 'm6', name: 'Phaltan Sub-District Mobile Hospital', nameKey: 'pois.phaltan_med', category: 'medical', latitude: 17.7837, longitude: 74.4328, contact: '108', capacity_status: 'available', landmark: 'Phaltan Civil Hospital' },
  { id: 'm7', name: 'Natepute Primary Health Post', nameKey: 'pois.natepute_med', category: 'medical', latitude: 17.6320, longitude: 74.5310, contact: '108', capacity_status: 'available', landmark: 'Natepute PHC Center' },
  { id: 'm8', name: 'Velapur Red Cross Medical Station', nameKey: 'pois.velapur_med', category: 'medical', latitude: 17.5810, longitude: 74.5690, contact: '108', capacity_status: 'available', landmark: 'Velapur ST Stand' },
  { id: 'm9', name: 'Wakhari Ringan Intensive Medical Unit', nameKey: 'pois.wakhari_med', category: 'medical', latitude: 17.6210, longitude: 75.1010, contact: '108', capacity_status: 'available', landmark: 'Wakhari Ringan Ground' },
  { id: 'm10', name: 'Pandharpur District Hospital & Trauma Care', nameKey: 'pois.pandharpur_med', category: 'medical', latitude: 17.6800, longitude: 75.3200, contact: '108', capacity_status: 'available', landmark: 'Pandharpur Civil Hospital' },

  // ── Drinking Water Points ─────────────────────────────────────────────
  { id: 'w1', name: 'Alandi Water Station', nameKey: 'pois.alandi_water', category: 'water', latitude: 18.6760, longitude: 73.8990, contact: null, capacity_status: 'available', landmark: 'Indrayani Ghat' },
  { id: 'w2', name: 'Pune Swargate Water Tanker Hub', nameKey: 'pois.pune_water', category: 'water', latitude: 18.5020, longitude: 73.8580, contact: null, capacity_status: 'available', landmark: 'Swargate Bus Stand' },
  { id: 'w3', name: 'Saswad Jal Seva Station', nameKey: 'pois.saswad_water', category: 'water', latitude: 18.3460, longitude: 74.0330, contact: null, capacity_status: 'available', landmark: 'Saswad Main Chowk' },
  { id: 'w4', name: 'Jejuri Jal Seva', nameKey: 'pois.jejuri_water', category: 'water', latitude: 18.2720, longitude: 74.1610, contact: null, capacity_status: 'available', landmark: 'Jejuri पायथा' },
  { id: 'w5', name: 'Lonand Water Point', nameKey: 'pois.lonand_water', category: 'water', latitude: 18.0200, longitude: 74.4500, contact: null, capacity_status: 'available', landmark: 'Lonand Highway Crossing' },
  { id: 'w6', name: 'Phaltan Municipal Water Post', nameKey: 'pois.phaltan_water', category: 'water', latitude: 17.7850, longitude: 74.4340, contact: null, capacity_status: 'available', landmark: 'Phaltan Nagar Parishad' },
  { id: 'w7', name: 'Velapur Pani Kendra', nameKey: 'pois.velapur_water', category: 'water', latitude: 17.5800, longitude: 74.5700, contact: null, capacity_status: 'available', landmark: 'Velapur Ring Road' },
  { id: 'w8', name: 'Wakhari Palkhi Jal Point', nameKey: 'pois.wakhari_water', category: 'water', latitude: 17.6190, longitude: 75.0990, contact: null, capacity_status: 'available', landmark: 'Wakhari Bypass' },
  { id: 'w9', name: 'Pandharpur Chandrabhaga Jal Seva', nameKey: 'pois.pandharpur_water', category: 'water', latitude: 17.6760, longitude: 75.3280, contact: null, capacity_status: 'available', landmark: 'Chandrabhaga River Bank' },

  // ── Parking Areas ─────────────────────────────────────────────────────
  { id: 'p1', name: 'Alandi Bus Stand Parking', nameKey: 'pois.alandi_parking', category: 'parking', latitude: 18.6790, longitude: 73.8970, contact: '9876543221', capacity_status: 'full', landmark: 'Alandi Palkhi Ground' },
  { id: 'p2', name: 'Pune Hadapsar Wari Vehicle Ground', nameKey: 'pois.pune_parking', category: 'parking', latitude: 18.5040, longitude: 73.9320, contact: '9876543222', capacity_status: 'available', landmark: 'Hadapsar Gadital' },
  { id: 'p3', name: 'Saswad Open Ground Wari Parking', nameKey: 'pois.saswad_parking', category: 'parking', latitude: 18.3420, longitude: 74.0350, contact: '9876543223', capacity_status: 'available', landmark: 'Saswad Ring Road' },
  { id: 'p4', name: 'Jejuri Base Dedicated Parking', nameKey: 'pois.jejuri_parking', category: 'parking', latitude: 18.2760, longitude: 74.1580, contact: '9876543224', capacity_status: 'available', landmark: 'Jejuri Bypass Ground' },
  { id: 'p5', name: 'Lonand Transport Vehicle Depot', nameKey: 'pois.lonand_parking', category: 'parking', latitude: 18.0170, longitude: 74.4520, contact: '9876543225', capacity_status: 'available', landmark: 'Lonand MIDC' },
  { id: 'p6', name: 'Phaltan Bypass Wari Parking', nameKey: 'pois.phaltan_parking', category: 'parking', latitude: 17.7860, longitude: 74.4300, contact: '9876543226', capacity_status: 'available', landmark: 'Phaltan Baramati Road' },
  { id: 'p7', name: 'Wakhari Ringan Parking Ground', nameKey: 'pois.wakhari_parking', category: 'parking', latitude: 17.6180, longitude: 75.0970, contact: '9876543227', capacity_status: 'available', landmark: 'Wakhari Palkhi Ground' },
  { id: 'p8', name: 'Pandharpur 65-Acre Mega Wari Parking', nameKey: 'pois.pandharpur_parking', category: 'parking', latitude: 17.6810, longitude: 75.3300, contact: '9876543220', capacity_status: 'available', landmark: '65 Acre Palkhi Maidan' },

  // ── Safety Camps & Police Desks ───────────────────────────────────────
  { id: 's1', name: 'Alandi Police Control Room & Help Desk', nameKey: 'pois.alandi_safety', category: 'safety', latitude: 18.6770, longitude: 73.8995, contact: '100', capacity_status: 'available', landmark: 'Temple Entrance Post' },
  { id: 's2', name: 'Pune Police & Women Safety Mobile Unit', nameKey: 'pois.pune_safety', category: 'safety', latitude: 18.5190, longitude: 73.8570, contact: '1091', capacity_status: 'available', landmark: 'FC Road Junction' },
  { id: 's3', name: 'Saswad Police & Lost Child Desk', nameKey: 'pois.saswad_safety', category: 'safety', latitude: 18.3450, longitude: 74.0325, contact: '100', capacity_status: 'available', landmark: 'Saswad Police Station' },
  { id: 's4', name: 'Jejuri Safety & Police Camp', nameKey: 'pois.jejuri_safety', category: 'safety', latitude: 18.2740, longitude: 74.1615, contact: '100', capacity_status: 'available', landmark: 'Jejuri Temple Steps' },
  { id: 's5', name: 'Lonand Police Help Booth', nameKey: 'pois.lonand_safety', category: 'safety', latitude: 18.0180, longitude: 74.4495, contact: '100', capacity_status: 'available', landmark: 'Lonand Chowki' },
  { id: 's6', name: 'Phaltan Police Command Center', nameKey: 'pois.phaltan_safety', category: 'safety', latitude: 17.7840, longitude: 74.4335, contact: '100', capacity_status: 'available', landmark: 'Phaltan City Police' },
  { id: 's7', name: 'Velapur Safety & Volunteer Desk', nameKey: 'pois.velapur_safety', category: 'safety', latitude: 17.5805, longitude: 74.5705, contact: '100', capacity_status: 'available', landmark: 'Velapur Grampanchayat' },
  { id: 's8', name: 'Wakhari Ringan Security Camp', nameKey: 'pois.wakhari_safety', category: 'safety', latitude: 17.6205, longitude: 75.1005, contact: '100', capacity_status: 'available', landmark: 'Wakhari Ringan Arena' },
  { id: 's9', name: 'Pandharpur Women & Child Safety Hub', nameKey: 'pois.pandharpur_women', category: 'safety', latitude: 17.6785, longitude: 75.3275, contact: '1091', capacity_status: 'available', landmark: 'Temple East Gate Safety Booth' },

  // ── Dharmashala & Rest Camps ──────────────────────────────────────────
  { id: 'st1', name: 'Alandi Bhakt Niwas Complex', nameKey: 'pois.alandi_stay', category: 'stay', latitude: 18.6780, longitude: 73.8965, contact: '9876543232', capacity_status: 'available', landmark: 'Near Alandi Temple' },
  { id: 'st2', name: 'Dehu Pilgrim Stay Ashram', nameKey: 'pois.dehu_stay', category: 'stay', latitude: 18.7130, longitude: 73.7680, contact: '9876543233', capacity_status: 'available', landmark: 'Dehu Temple Complex' },
  { id: 'st3', name: 'Jejuri Dharmashala', nameKey: 'pois.jejuri_stay', category: 'stay', latitude: 18.2750, longitude: 74.1590, contact: '9876543230', capacity_status: 'available', landmark: 'Near Temple Area' },
  { id: 'st4', name: 'Phaltan Warkari Tent Shelter', nameKey: 'pois.phaltan_stay', category: 'stay', latitude: 17.7810, longitude: 74.4350, contact: '9876543234', capacity_status: 'available', landmark: 'Phaltan Tent City' },
  { id: 'st5', name: 'Pandharpur Vishram Griha', nameKey: 'pois.pandharpur_stay', category: 'stay', latitude: 17.6770, longitude: 75.3250, contact: '9876543231', capacity_status: 'full', landmark: 'Near Main Temple' },
];

export const WARI_MILESTONES = [
  { id: 'alandi', nameKey: 'milestones.alandi', dateKey: 'dates.ashadh_shuddha_10', lat: 18.6776, lng: 73.8985, day: 1, isPalkhi: true },
  { id: 'dehu', nameKey: 'milestones.dehu', dateKey: 'dates.ashadh_shuddha_10', lat: 18.7140, lng: 73.7672, day: 1 },
  { id: 'pune', nameKey: 'milestones.pune', dateKey: 'dates.ashadh_shuddha_11', lat: 18.5204, lng: 73.8567, day: 2 },
  { id: 'loni_kalbhor', nameKey: 'milestones.loni_kalbhor', dateKey: 'dates.ashadh_shuddha_11', lat: 18.5062, lng: 73.9867, day: 3 },
  { id: 'saswad', nameKey: 'milestones.saswad', dateKey: 'dates.ashadh_shuddha_12', lat: 18.3454, lng: 74.0321, day: 4 },
  { id: 'jejuri', nameKey: 'milestones.jejuri', dateKey: 'dates.ashadh_shuddha_13', lat: 18.2731, lng: 74.1603, day: 5, isPalkhi: true },
  { id: 'valhe', nameKey: 'milestones.valhe', dateKey: 'dates.ashadh_shuddha_14', lat: 18.1500, lng: 74.2400, day: 6 },
  { id: 'lonand', nameKey: 'milestones.lonand', dateKey: 'dates.ashadh_shuddha_15', lat: 18.0186, lng: 74.4489, day: 7 },
  { id: 'taradgaon', nameKey: 'milestones.taradgaon', dateKey: 'dates.ashadh_krishna_1', lat: 17.9000, lng: 74.5400, day: 8 },
  { id: 'phaltan', nameKey: 'milestones.phaltan', dateKey: 'dates.ashadh_krishna_2', lat: 17.7837, lng: 74.4328, day: 9, isPalkhi: true },
  { id: 'baradwadi', nameKey: 'milestones.baradwadi', dateKey: 'dates.ashadh_krishna_3', lat: 17.6500, lng: 74.5100, day: 11 },
  { id: 'natepute', nameKey: 'milestones.natepute', dateKey: 'dates.ashadh_krishna_4', lat: 17.6300, lng: 74.5300, day: 12 },
  { id: 'velapur', nameKey: 'milestones.velapur', dateKey: 'dates.ashadh_krishna_5', lat: 17.5800, lng: 74.5700, day: 13 },
  { id: 'bhandishegaon', nameKey: 'milestones.bhandishegaon', dateKey: 'dates.ashadh_krishna_6', lat: 17.5500, lng: 74.5900, day: 14 },
  { id: 'wakhari', nameKey: 'milestones.wakhari', dateKey: 'dates.ashadh_krishna_8', lat: 17.6200, lng: 75.1000, day: 16 },
  { id: 'pandharpur', nameKey: 'milestones.pandharpur', dateKey: 'dates.ashadh_krishna_11', lat: 17.6778, lng: 75.3267, day: 18, isPalkhi: true },
];

export const EMERGENCY_CONTACTS = [
  { nameKey: 'emergency.central', number: '971', icon: 'Siren', color: '#DC2626' },
  { nameKey: 'emergency.police', number: '100', icon: 'Shield', color: '#2563EB' },
  { nameKey: 'emergency.ambulance', number: '108', icon: 'Ambulance', color: '#16A34A' },
  { nameKey: 'emergency.volunteer', number: '1800-123-4567', icon: 'HeadsetIcon', color: '#7C3AED' },
  { nameKey: 'emergency.women', number: '1091', icon: 'ShieldCheck', color: '#DB2777' },
];

export const SAFETY_TIPS = [
  { id: 'hydration', titleKey: 'tips.hydration_title', descKey: 'tips.hydration_desc', icon: 'Droplets' },
  { id: 'footwear', titleKey: 'tips.footwear_title', descKey: 'tips.footwear_desc', icon: 'Footprints' },
  { id: 'emergency', titleKey: 'tips.emergency_title', descKey: 'tips.emergency_desc', icon: 'Phone' },
  { id: 'green_route', titleKey: 'tips.green_route_title', descKey: 'tips.green_route_desc', icon: 'MapPin' },
  { id: 'group', titleKey: 'tips.group_title', descKey: 'tips.group_desc', icon: 'Users' },
  { id: 'luggage', titleKey: 'tips.luggage_title', descKey: 'tips.luggage_desc', icon: 'Backpack' },
];

export const POI_CATEGORIES = [
  { key: 'medical', labelKey: 'poi.medical', icon: 'Cross', color: '#EF4444', emoji: '🏥' },
  { key: 'water', labelKey: 'poi.water', icon: 'Droplets', color: '#0EA5E9', emoji: '💧' },
  { key: 'food', labelKey: 'poi.food', icon: 'UtensilsCrossed', color: '#F59E0B', emoji: '🍛' },
  { key: 'parking', labelKey: 'poi.parking', icon: 'ParkingCircle', color: '#64748B', emoji: '🅿️' },
  { key: 'safety', labelKey: 'poi.safety', icon: 'ShieldCheck', color: '#8B5CF6', emoji: '🛡️' },
  { key: 'stay', labelKey: 'poi.stay', icon: 'Bed', color: '#10B981', emoji: '🏠' },
];
